n_tasks = 8

[dates]
start_date = "1940-01-01"
end_date = "1940-01-01"

[bounds]
# min_lon = 145
# max_lon = 195
# min_lat = -60
# max_lat = -20

min_lon = 120
max_lon = 200
min_lat = -60
max_lat = -15

[source]
type = 's3'
provider = 'AWS'
env_auth = 'false'
region = 'us-west-2'
path = 'nsf-ncar-era5/'

[remote] # Two examples: s3 config and local path config; local path must be '/data/output', then mount a volume in docker-compose.yml
# type = 's3'
# provider = 'Mega'
# endpoint = 'https://s3.ca-west-1.s4.mega.io'
# access_key_id = ''
# secret_access_key = ''
# path = '/data/ncar/era5/'

# type = 'local'
# path = '/data/output'