[project]
name = "era5-s3-dl"
authors = [
  { name = "Mike Kittridge", email = "mullenkamp1@gmail.com" },
]
description = "A utility for downloading and subsetting ERA5 data from NCAR S3"
readme = "README.md"
dynamic = ["version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
]
requires-python = ">=3.10"
license = "Apache-2.0"
keywords = ["WRF", "WPS", "ERA5"]
dependencies = [
  "pendulum>=3.1",
  "typer>=0.12",
  "rclone-bin>=1.73",
  "typing-extensions"
]

[project.optional-dependencies]
sentry = ["sentry_sdk>=2.39"]

[project.scripts]
era5_dl = "era5_dl.era5_dl:app"

[project.urls]
Source = "https://github.com/envlib/era5-download"
Issues = "https://github.com/envlib/era5-download/issues"

[dependency-groups]
dev = [
  "pytest",
  "spyder-kernels==2.5.2",
  "black",
  "mypy",
  "ruff",
]

[tool.pytest.ini_options]
testpaths = ["era5_dl/tests"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.black]
target-version = ["py311"]
line-length = 120
skip-string-normalization = true

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = [
  "A",
  "ARG",
  "B",
  "C",
  "DTZ",
  "E",
  "EM",
  "F",
  "FBT",
  "I",
  "ICN",
  "ISC",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "S",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
]
ignore = [
  # Allow non-abstract empty methods in abstract base classes
  "B027",
  # Allow boolean positional values in function calls, like `dict.get(... True)`
  "FBT003",
  # Ignore checks for possible passwords
  "S105", "S106", "S107",
  # Ignore complexity
  "C901", "PLR0911", "PLR0912", "PLR0913", "PLR0915",
]
unfixable = [
  # Don't touch unused imports
  "F401",
]

[tool.ruff.lint.isort]
known-first-party = ["era5_dl"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**/*" = ["PLR2004", "S101", "TID252"]

[tool.coverage.run]
source_pkgs = ["era5_dl", "tests"]
branch = true
parallel = true

[tool.coverage.paths]
era5_dl = ["era5_dl"]
tests = ["era5_dl/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[build-system]
requires = ["hatchling>=1.26.1"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
    "/era5_dl",
]
exclude = [
    "/era5_dl/tests/*",
]

[tool.hatch.build.targets.wheel]
packages = ["era5_dl"]

[tool.hatch.version]
path = "era5_dl/__init__.py"
